// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkU8SFeC5zNpscwN4_i-V9nUl7O7yEqQ',
    appId: '1:254046441312:web:d3cc366cb5f08e2e8f9805',
    messagingSenderId: '254046441312',
    projectId: 'pokedex-24477',
    authDomain: 'pokedex-24477.firebaseapp.com',
    databaseURL: 'https://pokedex-24477-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-24477.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8nO1ouq1leoa_0Q6ddfvsjg5Iq2dSx4',
    appId: '1:254046441312:android:38409b21ab97dc088f9805',
    messagingSenderId: '254046441312',
    projectId: 'pokedex-24477',
    databaseURL: 'https://pokedex-24477-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-24477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-DLuiiAZJ0r1fsLqQ8A5NrWdCNuR5DF8',
    appId: '1:254046441312:ios:51a57bedf5cafd6c8f9805',
    messagingSenderId: '254046441312',
    projectId: 'pokedex-24477',
    databaseURL: 'https://pokedex-24477-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-24477.appspot.com',
    iosBundleId: 'com.example.pokedexapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-DLuiiAZJ0r1fsLqQ8A5NrWdCNuR5DF8',
    appId: '1:254046441312:ios:742d633fac25a3308f9805',
    messagingSenderId: '254046441312',
    projectId: 'pokedex-24477',
    databaseURL: 'https://pokedex-24477-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-24477.appspot.com',
    iosBundleId: 'com.example.pokedexapp.RunnerTests',
  );
}
